CREATE FUNCTION [dbo].FormatFlagApi (@inputString NVARCHAR(2))
RETURNS NVARCHAR(100)
AS
BEGIN
	RETURN N'https://flagsapi.com/' + @inputString + N'/flat/32.png';
END;
GO

--DECLARE @flagUrl NVARCHAR(100) = 'https://flagsapi.com/';

--INSERT INTO Countries (Name, Iso2Code, Iso3Code, DialCode, FlagUrl) VALUES 
--('Afghanistan', 'AF', 'AFG', '+93', @flagUrl + 'AF/flat/32.png'),
--('Albania', 'AL', 'ALB', '+355', @flagUrl + 'AL/flat/32.png'),
--('Algeria', 'DZ', 'DZA', '+213', @flagUrl + 'DZ/flat/32.png'),
--('Andorra', 'AD', 'AND', '+376', @flagUrl + 'AD/flat/32.png'),
--('Angola', 'AO', 'AGO', '+244', @flagUrl + 'AO/flat/32.png'),
--('Antigua and Barbuda', 'AG', 'ATG', '+1-268', @flagUrl + 'AG/flat/32.png'),
--('Argentina', 'AR', 'ARG', '+54', @flagUrl + 'AR/flat/32.png'),
--('Armenia', 'AM', 'ARM', '+374', @flagUrl + 'AM/flat/32.png'),
--('Australia', 'AU', 'AUS', '+61', @flagUrl + 'AU/flat/32.png'),
--('Austria', 'AT', 'AUT', '+43', @flagUrl + 'AT/flat/32.png'),
--('Azerbaijan', 'AZ', 'AZE', '+994', @flagUrl + 'AZ/flat/32.png'),
--('Bahamas', 'BS', 'BHS', '+1-242', @flagUrl + 'BS/flat/32.png'),
--('Bahrain', 'BH', 'BHR', '+973', @flagUrl + 'BH/flat/32.png'),
--('Bangladesh', 'BD', 'BGD', '+880', @flagUrl + 'BD/flat/32.png'),
--('Barbados', 'BB', 'BRB', '+1-246', @flagUrl + 'BB/flat/32.png'),
--('Belarus', 'BY', 'BLR', '+375', @flagUrl + 'BY/flat/32.png'),
--('Belgium', 'BE', 'BEL', '+32', @flagUrl + 'BE/flat/32.png'),
--('Belize', 'BZ', 'BLZ', '+501', @flagUrl + 'BZ/flat/32.png'),
--('Benin', 'BJ', 'BEN', '+229', @flagUrl + 'BJ/flat/32.png'),
--('Bhutan', 'BT', 'BTN', '+975', @flagUrl + 'BT/flat/32.png'),
--('Bolivia', 'BO', 'BOL', '+591', @flagUrl + 'BO/flat/32.png'),
--('Bosnia and Herzegovina', 'BA', 'BIH', '+387', @flagUrl + 'BA/flat/32.png'),
--('Botswana', 'BW', 'BWA', '+267', @flagUrl + 'BW/flat/32.png'),
--('Brazil', 'BR', 'BRA', '+55', @flagUrl + 'BR/flat/32.png'),
--('Brunei Darussalam', 'BN', 'BRN', '+673', @flagUrl + 'BN/flat/32.png'),
--('Bulgaria', 'BG', 'BGR', '+359', @flagUrl + 'BG/flat/32.png'),
--('Burkina Faso', 'BF', 'BFA', '+226', @flagUrl + 'BF/flat/32.png'),
--('Burundi', 'BI', 'BDI', '+257', @flagUrl + 'BI/flat/32.png'),
--('Cabo Verde', 'CV', 'CPV', '+238', @flagUrl + 'CV/flat/32.png'),
--('Cambodia', 'KH', 'KHM', '+855', @flagUrl + 'KH/flat/32.png'),
--('Cameroon', 'CM', 'CMR', '+237', @flagUrl + 'CM/flat/32.png'),
--('Canada', 'CA', 'CAN', '+1', @flagUrl + 'CA/flat/32.png'),
--('Central African Republic', 'CF', 'CAF', '+236', @flagUrl + 'CF/flat/32.png'),
--('Chad', 'TD', 'TCD', '+235', @flagUrl + 'TD/flat/32.png'),
--('Chile', 'CL', 'CHL', '+56', @flagUrl + 'CL/flat/32.png'),
--('China', 'CN', 'CHN', '+86', @flagUrl + 'CN/flat/32.png'),
--('Colombia', 'CO', 'COL', '+57', @flagUrl + 'CO/flat/32.png'),
--('Comoros', 'KM', 'COM', '+269', @flagUrl + 'KM/flat/32.png'),
--('Congo', 'CG', 'COG', '+242', @flagUrl + 'CG/flat/32.png'),
--('Congo, Democratic Republic of the', 'CD', 'COD', '+243', @flagUrl + 'CD/flat/32.png'),
--('Costa Rica', 'CR', 'CRI', '+506', @flagUrl + 'CR/flat/32.png'),
--('Croatia', 'HR', 'HRV', '+385', @flagUrl + 'HR/flat/32.png'),
--('Cuba', 'CU', 'CUB', '+53', @flagUrl + 'CU/flat/32.png'),
--('Cyprus', 'CY', 'CYP', '+357', @flagUrl + 'CY/flat/32.png'),
--('Czech Republic', 'CZ', 'CZE', '+420', @flagUrl + 'CZ/flat/32.png'),
--('Denmark', 'DK', 'DNK', '+45', @flagUrl + 'DK/flat/32.png'),
--('Djibouti', 'DJ', 'DJI', '+253', @flagUrl + 'DJ/flat/32.png'),
--('Dominica', 'DM', 'DMA', '+1-767', @flagUrl + 'DM/flat/32.png'),
--('Dominican Republic', 'DO', 'DOM', '+1-809', @flagUrl + 'DO/flat/32.png'),
--('East Timor', 'TL', 'TLS', '+670', @flagUrl + 'TL/flat/32.png'),
--('Ecuador', 'EC', 'ECU', '+593', @flagUrl + 'EC/flat/32.png'),
--('Egypt', 'EG', 'EGY', '+20', @flagUrl + 'EG/flat/32.png'),
--('El Salvador', 'SV', 'SLV', '+503', @flagUrl + 'SV/flat/32.png'),
--('Equatorial Guinea', 'GQ', 'GNQ', '+240', @flagUrl + 'GQ/flat/32.png'),
--('Eritrea', 'ER', 'ERI', '+291', @flagUrl + 'ER/flat/32.png'),
--('Estonia', 'EE', 'EST', '+372', @flagUrl + 'EE/flat/32.png'),
--('Eswatini', 'SZ', 'SWZ', '+268', @flagUrl + 'SZ/flat/32.png'),
--('Ethiopia', 'ET', 'ETH', '+251', @flagUrl + 'ET/flat/32.png'),
--('Fiji', 'FJ', 'FJI', '+679', @flagUrl + 'FJ/flat/32.png'),
--('Finland', 'FI', 'FIN', '+358', @flagUrl + 'FI/flat/32.png'),
--('France', 'FR', 'FRA', '+33', @flagUrl + 'FR/flat/32.png'),
--('Gabon', 'GA', 'GAB', '+241', @flagUrl + 'GA/flat/32.png'),
--('Gambia', 'GM', 'GMB', '+220', @flagUrl + 'GM/flat/32.png'),
--('Georgia', 'GE', 'GEO', '+995', @flagUrl + 'GE/flat/32.png'),
--('Germany', 'DE', 'DEU', '+49', @flagUrl + 'DE/flat/32.png'),
--('Ghana', 'GH', 'GHA', '+233', @flagUrl + 'GH/flat/32.png'),
--('Greece', 'GR', 'GRC', '+30', @flagUrl + 'GR/flat/32.png'),
--('Grenada', 'GD', 'GRD', '+1-473', @flagUrl + 'GD/flat/32.png'),
--('Guatemala', 'GT', 'GTM', '+502', @flagUrl + 'GT/flat/32.png'),
--('Guinea', 'GN', 'GIN', '+224', @flagUrl + 'GN/flat/32.png'),
--('Guinea-Bissau', 'GW', 'GNB', '+245', @flagUrl + 'GW/flat/32.png'),
--('Guyana', 'GY', 'GUY', '+592', @flagUrl + 'GY/flat/32.png'),
--('Haiti', 'HT', 'HTI', '+509', @flagUrl + 'HT/flat/32.png'),
--('Honduras', 'HN', 'HND', '+504', @flagUrl + 'HN/flat/32.png'),
--('Hungary', 'HU', 'HUN', '+36', @flagUrl + 'HU/flat/32.png'),
--('Iceland', 'IS', 'ISL', '+354', @flagUrl + 'IS/flat/32.png'),
--('India', 'IN', 'IND', '+91', @flagUrl + 'IN/flat/32.png'),
--('Indonesia', 'ID', 'IDN', '+62', @flagUrl + 'ID/flat/32.png'),
--('Iran', 'IR', 'IRN', '+98', @flagUrl + 'IR/flat/32.png'),
--('Iraq', 'IQ', 'IRQ', '+964', @flagUrl + 'IQ/flat/32.png'),
--('Ireland', 'IE', 'IRL', '+353', @flagUrl + 'IE/flat/32.png'),
--('Israel', 'IL', 'ISR', '+972', @flagUrl + 'IL/flat/32.png'),
--('Italy', 'IT', 'ITA', '+39', @flagUrl + 'IT/flat/32.png'),
--('Jamaica', 'JM', 'JAM', '+1-876', @flagUrl + 'JM/flat/32.png'),
--('Japan', 'JP', 'JPN', '+81', @flagUrl + 'JP/flat/32.png'),
--('Jordan', 'JO', 'JOR', '+962', @flagUrl + 'JO/flat/32.png'),
--('Kazakhstan', 'KZ', 'KAZ', '+7', @flagUrl + 'KZ/flat/32.png'),
--('Kenya', 'KE', 'KEN', '+254', @flagUrl + 'KE/flat/32.png'),
--('Kiribati', 'KI', 'KIR', '+686', @flagUrl + 'KI/flat/32.png'),
--('Korea, North', 'KP', 'PRK', '+850', @flagUrl + 'KP/flat/32.png'),
--('Korea, South', 'KR', 'KOR', '+82', @flagUrl + 'KR/flat/32.png'),
--('Kosovo', 'XK', 'XKX', '+383', @flagUrl + 'XK/flat/32.png'),
--('Kuwait', 'KW', 'KWT', '+965', @flagUrl + 'KW/flat/32.png'),
--('Kyrgyzstan', 'KG', 'KGZ', '+996', @flagUrl + 'KG/flat/32.png'),
--('Lao People''s Democratic Republic', 'LA', 'LAO', '+856', @flagUrl + 'LA/flat/32.png'),
--('Latvia', 'LV', 'LVA', '+371', @flagUrl + 'LV/flat/32.png'),
--('Lebanon', 'LB', 'LBN', '+961', @flagUrl + 'LB/flat/32.png'),
--('Lesotho', 'LS', 'LSO', '+266', @flagUrl + 'LS/flat/32.png'),
--('Liberia', 'LR', 'LBR', '+231', @flagUrl + 'LR/flat/32.png'),
--('Libya', 'LY', 'LBY', '+218', @flagUrl + 'LY/flat/32.png'),
--('Liechtenstein', 'LI', 'LIE', '+423', @flagUrl + 'LI/flat/32.png'),
--('Lithuania', 'LT', 'LTU', '+370', @flagUrl + 'LT/flat/32.png'),
--('Luxembourg', 'LU', 'LUX', '+352', @flagUrl + 'LU/flat/32.png'),
--('Madagascar', 'MG', 'MDG', '+261', @flagUrl + 'MG/flat/32.png'),
--('Malawi', 'MW', 'MWI', '+265', @flagUrl + 'MW/flat/32.png'),
--('Malaysia', 'MY', 'MYS', '+60', @flagUrl + 'MY/flat/32.png'),
--('Maldives', 'MV', 'MDV', '+960', @flagUrl + 'MV/flat/32.png'),
--('Mali', 'ML', 'MLI', '+223', @flagUrl + 'ML/flat/32.png'),
--('Malta', 'MT', 'MLT', '+356', @flagUrl + 'MT/flat/32.png'),
--('Marshall Islands', 'MH', 'MHL', '+692', @flagUrl + 'MH/flat/32.png'),
--('Mauritania', 'MR', 'MRT', '+222', @flagUrl + 'MR/flat/32.png'),
--('Mauritius', 'MU', 'MUS', '+230', @flagUrl + 'MU/flat/32.png'),
--('Mexico', 'MX', 'MEX', '+52', @flagUrl + 'MX/flat/32.png'),
--('Micronesia', 'FM', 'FSM', '+691', @flagUrl + 'FM/flat/32.png'),
--('Moldova', 'MD', 'MDA', '+373', @flagUrl + 'MD/flat/32.png'),
--('Monaco', 'MC', 'MCO', '+377', @flagUrl + 'MC/flat/32.png'),
--('Mongolia', 'MN', 'MNG', '+976', @flagUrl + 'MN/flat/32.png'),
--('Montenegro', 'ME', 'MNE', '+382', @flagUrl + 'ME/flat/32.png'),
--('Morocco', 'MA', 'MAR', '+212', @flagUrl + 'MA/flat/32.png'),
--('Mozambique', 'MZ', 'MOZ', '+258', @flagUrl + 'MZ/flat/32.png'),
--('Myanmar', 'MM', 'MMR', '+95', @flagUrl + 'MM/flat/32.png'),
--('Namibia', 'NA', 'NAM', '+264', @flagUrl + 'NA/flat/32.png'),
--('Nauru', 'NR', 'NRU', '+674', @flagUrl + 'NR/flat/32.png'),
--('Nepal', 'NP', 'NPL', '+977', @flagUrl + 'NP/flat/32.png'),
--('Netherlands', 'NL', 'NLD', '+31', @flagUrl + 'NL/flat/32.png'),
--('New Zealand', 'NZ', 'NZL', '+64', @flagUrl + 'NZ/flat/32.png'),
--('Nicaragua', 'NI', 'NIC', '+505', @flagUrl + 'NI/flat/32.png'),
--('Niger', 'NE', 'NER', '+227', @flagUrl + 'NE/flat/32.png'),
--('Nigeria', 'NG', 'NGA', '+234', @flagUrl + 'NG/flat/32.png'),
--('North Macedonia', 'MK', 'MKD', '+389', @flagUrl + 'MK/flat/32.png'),
--('Norway', 'NO', 'NOR', '+47', @flagUrl + 'NO/flat/32.png'),
--('Oman', 'OM', 'OMN', '+968', @flagUrl + 'OM/flat/32.png'),
--('Pakistan', 'PK', 'PAK', '+92', @flagUrl + 'PK/flat/32.png'),
--('Palau', 'PW', 'PLW', '+680', @flagUrl + 'PW/flat/32.png'),
--('Palestine', 'PS', 'PSE', '+970', @flagUrl + 'PS/flat/32.png'),
--('Panama', 'PA', 'PAN', '+507', @flagUrl + 'PA/flat/32.png'),
--('Papua New Guinea', 'PG', 'PNG', '+675', @flagUrl + 'PG/flat/32.png'),
--('Paraguay', 'PY', 'PRY', '+595', @flagUrl + 'PY/flat/32.png'),
--('Peru', 'PE', 'PER', '+51', @flagUrl + 'PE/flat/32.png'),
--('Philippines', 'PH', 'PHL', '+63', @flagUrl + 'PH/flat/32.png'),
--('Poland', 'PL', 'POL', '+48', @flagUrl + 'PL/flat/32.png'),
--('Portugal', 'PT', 'PRT', '+351', @flagUrl + 'PT/flat/32.png'),
--('Qatar', 'QA', 'QAT', '+974', @flagUrl + 'QA/flat/32.png'),
--('Romania', 'RO', 'ROU', '+40', @flagUrl + 'RO/flat/32.png'),
--('Russia', 'RU', 'RUS', '+7', @flagUrl + 'RU/flat/32.png'),
--('Rwanda', 'RW', 'RWA', '+250', @flagUrl + 'RW/flat/32.png'),
--('Saint Kitts and Nevis', 'KN', 'KNA', '+1-869', @flagUrl + 'KN/flat/32.png'),
--('Saint Lucia', 'LC', 'LCA', '+1-758', @flagUrl + 'LC/flat/32.png'),
--('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1-784', @flagUrl + 'VC/flat/32.png'),
--('Samoa', 'WS', 'WSM', '+685', @flagUrl + 'WS/flat/32.png'),
--('San Marino', 'SM', 'SMR', '+378', @flagUrl + 'SM/flat/32.png'),
--('Sao Tome and Principe', 'ST', 'STP', '+239', @flagUrl + 'ST/flat/32.png'),
--('Saudi Arabia', 'SA', 'SAU', '+966', @flagUrl + 'SA/flat/32.png'),
--('Senegal', 'SN', 'SEN', '+221', @flagUrl + 'SN/flat/32.png'),
--('Serbia', 'RS', 'SRB', '+381', @flagUrl + 'RS/flat/32.png'),
--('Seychelles', 'SC', 'SYC', '+248', @flagUrl + 'SC/flat/32.png'),
--('Sierra Leone', 'SL', 'SLE', '+232', @flagUrl + 'SL/flat/32.png'),
--('Singapore', 'SG', 'SGP', '+65', @flagUrl + 'SG/flat/32.png'),
--('Slovakia', 'SK', 'SVK', '+421', @flagUrl + 'SK/flat/32.png'),
--('Slovenia', 'SI', 'SVN', '+386', @flagUrl + 'SI/flat/32.png'),
--('Solomon Islands', 'SB', 'SLB', '+677', @flagUrl + 'SB/flat/32.png'),
--('Somalia', 'SO', 'SOM', '+252', @flagUrl + 'SO/flat/32.png'),
--('South Africa', 'ZA', 'ZAF', '+27', @flagUrl + 'ZA/flat/32.png'),
--('South Sudan', 'SS', 'SSD', '+211', @flagUrl + 'SS/flat/32.png'),
--('Spain', 'ES', 'ESP', '+34', @flagUrl + 'ES/flat/32.png'),
--('Sri Lanka', 'LK', 'LKA', '+94', @flagUrl + 'LK/flat/32.png'),
--('Sudan', 'SD', 'SDN', '+249', @flagUrl + 'SD/flat/32.png'),
--('Suriname', 'SR', 'SUR', '+597', @flagUrl + 'SR/flat/32.png'),
--('Sweden', 'SE', 'SWE', '+46', @flagUrl + 'SE/flat/32.png'),
--('Switzerland', 'CH', 'CHE', '+41', @flagUrl + 'CH/flat/32.png'),
--('Syria', 'SY', 'SYR', '+963', @flagUrl + 'SY/flat/32.png'),
--('Taiwan', 'TW', 'TWN', '+886', @flagUrl + 'TW/flat/32.png'),
--('Tajikistan', 'TJ', 'TJK', '+992', @flagUrl + 'TJ/flat/32.png'),
--('Tanzania', 'TZ', 'TZA', '+255', @flagUrl + 'TZ/flat/32.png'),
--('Thailand', 'TH', 'THA', '+66', @flagUrl + 'TH/flat/32.png'),
--('Togo', 'TG', 'TGO', '+228', @flagUrl + 'TG/flat/32.png'),
--('Tonga', 'TO', 'TON', '+676', @flagUrl + 'TO/flat/32.png'),
--('Trinidad and Tobago', 'TT', 'TTO', '+1-868', @flagUrl + 'TT/flat/32.png'),
--('Tunisia', 'TN', 'TUN', '+216', @flagUrl + 'TN/flat/32.png'),
--('Turkey', 'TR', 'TUR', '+90', @flagUrl + 'TR/flat/32.png'),
--('Turkmenistan', 'TM', 'TKM', '+993', @flagUrl + 'TM/flat/32.png'),
--('Tuvalu', 'TV', 'TUV', '+688', @flagUrl + 'TV/flat/32.png'),
--('Uganda', 'UG', 'UGA', '+256', @flagUrl + 'UG/flat/32.png'),
--('Ukraine', 'UA', 'UKR', '+380', @flagUrl + 'UA/flat/32.png'),
--('United Arab Emirates', 'AE', 'ARE', '+971', @flagUrl + 'AE/flat/32.png'),
--('United Kingdom', 'GB', 'GBR', '+44', @flagUrl + 'GB/flat/32.png'),
--('United States of America', 'US', 'USA', '+1', @flagUrl + 'US/flat/32.png'),
--('Uruguay', 'UY', 'URY', '+598', @flagUrl + 'UY/flat/32.png'),
--('Uzbekistan', 'UZ', 'UZB', '+998', @flagUrl + 'UZ/flat/32.png'),
--('Vanuatu', 'VU', 'VUT', '+678', @flagUrl + 'VU/flat/32.png'),
--('Vatican City', 'VA', 'VAT', '+379', @flagUrl + 'VA/flat/32.png'),
--('Venezuela', 'VE', 'VEN', '+58', @flagUrl + 'VE/flat/32.png'),
--('Vietnam', 'VN', 'VNM', '+84', @flagUrl + 'VN/flat/32.png'),
--('Yemen', 'YE', 'YEM', '+967', @flagUrl + 'YE/flat/32.png'),
--('Zambia', 'ZM', 'ZMB', '+260', @flagUrl + 'ZM/flat/32.png'),
--('Zimbabwe', 'ZW', 'ZWE', '+263', @flagUrl + 'ZW/flat/32.png');

INSERT INTO Country (Name, Iso2Code, Iso3Code, DialCode, FlagUrl) VALUES 
('Afghanistan', 'AF', 'AFG', '+93', [dbo].FormatFlagApi('AF')),
('Albania', 'AL', 'ALB', '+355', [dbo].FormatFlagApi('AL')),
('Algeria', 'DZ', 'DZA', '+213', [dbo].FormatFlagApi('DZ')),
('Andorra', 'AD', 'AND', '+376', [dbo].FormatFlagApi('AD')),
('Angola', 'AO', 'AGO', '+244', [dbo].FormatFlagApi('AO')),
('Antigua and Barbuda', 'AG', 'ATG', '+1-268', [dbo].FormatFlagApi('AG')),
('Argentina', 'AR', 'ARG', '+54', [dbo].FormatFlagApi('AR')),
('Armenia', 'AM', 'ARM', '+374', [dbo].FormatFlagApi('AM')),
('Australia', 'AU', 'AUS', '+61', [dbo].FormatFlagApi('AU')),
('Austria', 'AT', 'AUT', '+43', [dbo].FormatFlagApi('AT')),
('Azerbaijan', 'AZ', 'AZE', '+994', [dbo].FormatFlagApi('AZ')),
('Bahamas', 'BS', 'BHS', '+1-242', [dbo].FormatFlagApi('BS')),
('Bahrain', 'BH', 'BHR', '+973', [dbo].FormatFlagApi('BH')),
('Bangladesh', 'BD', 'BGD', '+880', [dbo].FormatFlagApi('BD')),
('Barbados', 'BB', 'BRB', '+1-246', [dbo].FormatFlagApi('BB')),
('Belarus', 'BY', 'BLR', '+375', [dbo].FormatFlagApi('BY')),
('Belgium', 'BE', 'BEL', '+32', [dbo].FormatFlagApi('BE')),
('Belize', 'BZ', 'BLZ', '+501', [dbo].FormatFlagApi('BZ')),
('Benin', 'BJ', 'BEN', '+229', [dbo].FormatFlagApi('BJ')),
('Bhutan', 'BT', 'BTN', '+975', [dbo].FormatFlagApi('BT')),
('Bolivia', 'BO', 'BOL', '+591', [dbo].FormatFlagApi('BO')),
('Bosnia and Herzegovina', 'BA', 'BIH', '+387', [dbo].FormatFlagApi('BA')),
('Botswana', 'BW', 'BWA', '+267', [dbo].FormatFlagApi('BW')),
('Brazil', 'BR', 'BRA', '+55', [dbo].FormatFlagApi('BR')),
('Brunei Darussalam', 'BN', 'BRN', '+673', [dbo].FormatFlagApi('BN')),
('Bulgaria', 'BG', 'BGR', '+359', [dbo].FormatFlagApi('BG')),
('Burkina Faso', 'BF', 'BFA', '+226', [dbo].FormatFlagApi('BF')),
('Burundi', 'BI', 'BDI', '+257', [dbo].FormatFlagApi('BI')),
('Cabo Verde', 'CV', 'CPV', '+238', [dbo].FormatFlagApi('CV')),
('Cambodia', 'KH', 'KHM', '+855', [dbo].FormatFlagApi('KH')),
('Cameroon', 'CM', 'CMR', '+237', [dbo].FormatFlagApi('CM')),
('Canada', 'CA', 'CAN', '+1', [dbo].FormatFlagApi('CA')),
('Central African Republic', 'CF', 'CAF', '+236', [dbo].FormatFlagApi('CF')),
('Chad', 'TD', 'TCD', '+235', [dbo].FormatFlagApi('TD')),
('Chile', 'CL', 'CHL', '+56', [dbo].FormatFlagApi('CL')),
('China', 'CN', 'CHN', '+86', [dbo].FormatFlagApi('CN')),
('Colombia', 'CO', 'COL', '+57', [dbo].FormatFlagApi('CO')),
('Comoros', 'KM', 'COM', '+269', [dbo].FormatFlagApi('KM')),
('Congo', 'CG', 'COG', '+242', [dbo].FormatFlagApi('CG')),
('Congo, Democratic Republic of the', 'CD', 'COD', '+243', [dbo].FormatFlagApi('CD')),
('Costa Rica', 'CR', 'CRI', '+506', [dbo].FormatFlagApi('CR')),
('Croatia', 'HR', 'HRV', '+385', [dbo].FormatFlagApi('HR')),
('Cuba', 'CU', 'CUB', '+53', [dbo].FormatFlagApi('CU')),
('Cyprus', 'CY', 'CYP', '+357', [dbo].FormatFlagApi('CY')),
('Czech Republic', 'CZ', 'CZE', '+420', [dbo].FormatFlagApi('CZ')),
('Denmark', 'DK', 'DNK', '+45', [dbo].FormatFlagApi('DK')),
('Djibouti', 'DJ', 'DJI', '+253', [dbo].FormatFlagApi('DJ')),
('Dominica', 'DM', 'DMA', '+1-767', [dbo].FormatFlagApi('DM')),
('Dominican Republic', 'DO', 'DOM', '+1-809', [dbo].FormatFlagApi('DO')),
('East Timor', 'TL', 'TLS', '+670', [dbo].FormatFlagApi('TL')),
('Ecuador', 'EC', 'ECU', '+593', [dbo].FormatFlagApi('EC')),
('Egypt', 'EG', 'EGY', '+20', [dbo].FormatFlagApi('EG')),
('El Salvador', 'SV', 'SLV', '+503', [dbo].FormatFlagApi('SV')),
('Equatorial Guinea', 'GQ', 'GNQ', '+240', [dbo].FormatFlagApi('GQ')),
('Eritrea', 'ER', 'ERI', '+291', [dbo].FormatFlagApi('ER')),
('Estonia', 'EE', 'EST', '+372', [dbo].FormatFlagApi('EE')),
('Eswatini', 'SZ', 'SWZ', '+268', [dbo].FormatFlagApi('SZ')),
('Ethiopia', 'ET', 'ETH', '+251', [dbo].FormatFlagApi('ET')),
('Fiji', 'FJ', 'FJI', '+679', [dbo].FormatFlagApi('FJ')),
('Finland', 'FI', 'FIN', '+358', [dbo].FormatFlagApi('FI')),
('France', 'FR', 'FRA', '+33', [dbo].FormatFlagApi('FR')),
('Gabon', 'GA', 'GAB', '+241', [dbo].FormatFlagApi('GA')),
('Gambia', 'GM', 'GMB', '+220', [dbo].FormatFlagApi('GM')),
('Georgia', 'GE', 'GEO', '+995', [dbo].FormatFlagApi('GE')),
('Germany', 'DE', 'DEU', '+49', [dbo].FormatFlagApi('DE')),
('Ghana', 'GH', 'GHA', '+233', [dbo].FormatFlagApi('GH')),
('Greece', 'GR', 'GRC', '+30', [dbo].FormatFlagApi('GR')),
('Grenada', 'GD', 'GRD', '+1-473', [dbo].FormatFlagApi('GD')),
('Guatemala', 'GT', 'GTM', '+502', [dbo].FormatFlagApi('GT')),
('Guinea', 'GN', 'GIN', '+224', [dbo].FormatFlagApi('GN')),
('Guinea-Bissau', 'GW', 'GNB', '+245', [dbo].FormatFlagApi('GW')),
('Guyana', 'GY', 'GUY', '+592', [dbo].FormatFlagApi('GY')),
('Haiti', 'HT', 'HTI', '+509', [dbo].FormatFlagApi('HT')),
('Honduras', 'HN', 'HND', '+504', [dbo].FormatFlagApi('HN')),
('Hungary', 'HU', 'HUN', '+36', [dbo].FormatFlagApi('HU')),
('Iceland', 'IS', 'ISL', '+354', [dbo].FormatFlagApi('IS')),
('India', 'IN', 'IND', '+91', [dbo].FormatFlagApi('IN')),
('Indonesia', 'ID', 'IDN', '+62', [dbo].FormatFlagApi('ID')),
('Iran', 'IR', 'IRN', '+98', [dbo].FormatFlagApi('IR')),
('Iraq', 'IQ', 'IRQ', '+964', [dbo].FormatFlagApi('IQ')),
('Ireland', 'IE', 'IRL', '+353', [dbo].FormatFlagApi('IE')),
('Israel', 'IL', 'ISR', '+972', [dbo].FormatFlagApi('IL')),
('Italy', 'IT', 'ITA', '+39', [dbo].FormatFlagApi('IT')),
('Jamaica', 'JM', 'JAM', '+1-876', [dbo].FormatFlagApi('JM')),
('Japan', 'JP', 'JPN', '+81', [dbo].FormatFlagApi('JP')),
('Jordan', 'JO', 'JOR', '+962', [dbo].FormatFlagApi('JO')),
('Kazakhstan', 'KZ', 'KAZ', '+7', [dbo].FormatFlagApi('KZ')),
('Kenya', 'KE', 'KEN', '+254', [dbo].FormatFlagApi('KE')),
('Kiribati', 'KI', 'KIR', '+686', [dbo].FormatFlagApi('KI')),
('Korea, North', 'KP', 'PRK', '+850', [dbo].FormatFlagApi('KP')),
('Korea, South', 'KR', 'KOR', '+82', [dbo].FormatFlagApi('KR')),
('Kosovo', 'XK', 'XKX', '+383', [dbo].FormatFlagApi('XK')),
('Kuwait', 'KW', 'KWT', '+965', [dbo].FormatFlagApi('KW')),
('Kyrgyzstan', 'KG', 'KGZ', '+996', [dbo].FormatFlagApi('KG')),
('Lao People''s Democratic Republic', 'LA', 'LAO', '+856', [dbo].FormatFlagApi('LA')),
('Latvia', 'LV', 'LVA', '+371', [dbo].FormatFlagApi('LV')),
('Lebanon', 'LB', 'LBN', '+961', [dbo].FormatFlagApi('LB')),
('Lesotho', 'LS', 'LSO', '+266', [dbo].FormatFlagApi('LS')),
('Liberia', 'LR', 'LBR', '+231', [dbo].FormatFlagApi('LR')),
('Libya', 'LY', 'LBY', '+218', [dbo].FormatFlagApi('LY')),
('Liechtenstein', 'LI', 'LIE', '+423', [dbo].FormatFlagApi('LI')),
('Lithuania', 'LT', 'LTU', '+370', [dbo].FormatFlagApi('LT')),
('Luxembourg', 'LU', 'LUX', '+352', [dbo].FormatFlagApi('LU')),
('Madagascar', 'MG', 'MDG', '+261', [dbo].FormatFlagApi('MG')),
('Malawi', 'MW', 'MWI', '+265', [dbo].FormatFlagApi('MW')),
('Malaysia', 'MY', 'MYS', '+60', [dbo].FormatFlagApi('MY')),
('Maldives', 'MV', 'MDV', '+960', [dbo].FormatFlagApi('MV')),
('Mali', 'ML', 'MLI', '+223', [dbo].FormatFlagApi('ML')),
('Malta', 'MT', 'MLT', '+356', [dbo].FormatFlagApi('MT')),
('Marshall Islands', 'MH', 'MHL', '+692', [dbo].FormatFlagApi('MH')),
('Mauritania', 'MR', 'MRT', '+222', [dbo].FormatFlagApi('MR')),
('Mauritius', 'MU', 'MUS', '+230', [dbo].FormatFlagApi('MU')),
('Mexico', 'MX', 'MEX', '+52', [dbo].FormatFlagApi('MX')),
('Micronesia', 'FM', 'FSM', '+691', [dbo].FormatFlagApi('FM')),
('Moldova', 'MD', 'MDA', '+373', [dbo].FormatFlagApi('MD')),
('Monaco', 'MC', 'MCO', '+377', [dbo].FormatFlagApi('MC')),
('Mongolia', 'MN', 'MNG', '+976', [dbo].FormatFlagApi('MN')),
('Montenegro', 'ME', 'MNE', '+382', [dbo].FormatFlagApi('ME')),
('Morocco', 'MA', 'MAR', '+212', [dbo].FormatFlagApi('MA')),
('Mozambique', 'MZ', 'MOZ', '+258', [dbo].FormatFlagApi('MZ')),
('Myanmar', 'MM', 'MMR', '+95', [dbo].FormatFlagApi('MM')),
('Namibia', 'NA', 'NAM', '+264', [dbo].FormatFlagApi('NA')),
('Nauru', 'NR', 'NRU', '+674', [dbo].FormatFlagApi('NR')),
('Nepal', 'NP', 'NPL', '+977', [dbo].FormatFlagApi('NP')),
('Netherlands', 'NL', 'NLD', '+31', [dbo].FormatFlagApi('NL')),
('New Zealand', 'NZ', 'NZL', '+64', [dbo].FormatFlagApi('NZ')),
('Nicaragua', 'NI', 'NIC', '+505', [dbo].FormatFlagApi('NI')),
('Niger', 'NE', 'NER', '+227', [dbo].FormatFlagApi('NE')),
('Nigeria', 'NG', 'NGA', '+234', [dbo].FormatFlagApi('NG')),
('North Macedonia', 'MK', 'MKD', '+389', [dbo].FormatFlagApi('MK')),
('Norway', 'NO', 'NOR', '+47', [dbo].FormatFlagApi('NO')),
('Oman', 'OM', 'OMN', '+968', [dbo].FormatFlagApi('OM')),
('Pakistan', 'PK', 'PAK', '+92', [dbo].FormatFlagApi('PK')),
('Palau', 'PW', 'PLW', '+680', [dbo].FormatFlagApi('PW')),
('Palestine', 'PS', 'PSE', '+970', [dbo].FormatFlagApi('PS')),
('Panama', 'PA', 'PAN', '+507', [dbo].FormatFlagApi('PA')),
('Papua New Guinea', 'PG', 'PNG', '+675', [dbo].FormatFlagApi('PG')),
('Paraguay', 'PY', 'PRY', '+595', [dbo].FormatFlagApi('PY')),
('Peru', 'PE', 'PER', '+51', [dbo].FormatFlagApi('PE')),
('Philippines', 'PH', 'PHL', '+63', [dbo].FormatFlagApi('PH')),
('Poland', 'PL', 'POL', '+48', [dbo].FormatFlagApi('PL')),
('Portugal', 'PT', 'PRT', '+351', [dbo].FormatFlagApi('PT')),
('Qatar', 'QA', 'QAT', '+974', [dbo].FormatFlagApi('QA')),
('Romania', 'RO', 'ROU', '+40', [dbo].FormatFlagApi('RO')),
('Russia', 'RU', 'RUS', '+7', [dbo].FormatFlagApi('RU')),
('Rwanda', 'RW', 'RWA', '+250', [dbo].FormatFlagApi('RW')),
('Saint Kitts and Nevis', 'KN', 'KNA', '+1-869', [dbo].FormatFlagApi('KN')),
('Saint Lucia', 'LC', 'LCA', '+1-758', [dbo].FormatFlagApi('LC')),
('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1-784', [dbo].FormatFlagApi('VC')),
('Samoa', 'WS', 'WSM', '+685', [dbo].FormatFlagApi('WS')),
('San Marino', 'SM', 'SMR', '+378', [dbo].FormatFlagApi('SM')),
('Sao Tome and Principe', 'ST', 'STP', '+239', [dbo].FormatFlagApi('ST')),
('Saudi Arabia', 'SA', 'SAU', '+966', [dbo].FormatFlagApi('SA')),
('Senegal', 'SN', 'SEN', '+221', [dbo].FormatFlagApi('SN')),
('Serbia', 'RS', 'SRB', '+381', [dbo].FormatFlagApi('RS')),
('Seychelles', 'SC', 'SYC', '+248', [dbo].FormatFlagApi('SC')),
('Sierra Leone', 'SL', 'SLE', '+232', [dbo].FormatFlagApi('SL')),
('Singapore', 'SG', 'SGP', '+65', [dbo].FormatFlagApi('SG')),
('Slovakia', 'SK', 'SVK', '+421', [dbo].FormatFlagApi('SK')),
('Slovenia', 'SI', 'SVN', '+386', [dbo].FormatFlagApi('SI')),
('Solomon Islands', 'SB', 'SLB', '+677', [dbo].FormatFlagApi('SB')),
('Somalia', 'SO', 'SOM', '+252', [dbo].FormatFlagApi('SO')),
('South Africa', 'ZA', 'ZAF', '+27', [dbo].FormatFlagApi('ZA')),
('South Sudan', 'SS', 'SSD', '+211', [dbo].FormatFlagApi('SS')),
('Spain', 'ES', 'ESP', '+34', [dbo].FormatFlagApi('ES')),
('Sri Lanka', 'LK', 'LKA', '+94', [dbo].FormatFlagApi('LK')),
('Sudan', 'SD', 'SDN', '+249', [dbo].FormatFlagApi('SD')),
('Suriname', 'SR', 'SUR', '+597', [dbo].FormatFlagApi('SR')),
('Sweden', 'SE', 'SWE', '+46', [dbo].FormatFlagApi('SE')),
('Switzerland', 'CH', 'CHE', '+41', [dbo].FormatFlagApi('CH')),
('Syria', 'SY', 'SYR', '+963', [dbo].FormatFlagApi('SY')),
('Taiwan', 'TW', 'TWN', '+886', [dbo].FormatFlagApi('TW')),
('Tajikistan', 'TJ', 'TJK', '+992', [dbo].FormatFlagApi('TJ')),
('Tanzania', 'TZ', 'TZA', '+255', [dbo].FormatFlagApi('TZ')),
('Thailand', 'TH', 'THA', '+66', [dbo].FormatFlagApi('TH')),
('Togo', 'TG', 'TGO', '+228', [dbo].FormatFlagApi('TG')),
('Tonga', 'TO', 'TON', '+676', [dbo].FormatFlagApi('TO')),
('Trinidad and Tobago', 'TT', 'TTO', '+1-868', [dbo].FormatFlagApi('TT')),
('Tunisia', 'TN', 'TUN', '+216', [dbo].FormatFlagApi('TN')),
('Turkey', 'TR', 'TUR', '+90', [dbo].FormatFlagApi('TR')),
('Turkmenistan', 'TM', 'TKM', '+993', [dbo].FormatFlagApi('TM')),
('Tuvalu', 'TV', 'TUV', '+688', [dbo].FormatFlagApi('TV')),
('Uganda', 'UG', 'UGA', '+256', [dbo].FormatFlagApi('UG')),
('Ukraine', 'UA', 'UKR', '+380', [dbo].FormatFlagApi('UA')),
('United Arab Emirates', 'AE', 'ARE', '+971', [dbo].FormatFlagApi('AE')),
('United Kingdom', 'GB', 'GBR', '+44', [dbo].FormatFlagApi('GB')),
('United States of America', 'US', 'USA', '+1', [dbo].FormatFlagApi('US')),
('Uruguay', 'UY', 'URY', '+598', [dbo].FormatFlagApi('UY')),
('Uzbekistan', 'UZ', 'UZB', '+998', [dbo].FormatFlagApi('UZ')),
('Vanuatu', 'VU', 'VUT', '+678', [dbo].FormatFlagApi('VU')),
('Vatican City', 'VA', 'VAT', '+379', [dbo].FormatFlagApi('VA')),
('Venezuela', 'VE', 'VEN', '+58', [dbo].FormatFlagApi('VE')),
('Vietnam', 'VN', 'VNM', '+84', [dbo].FormatFlagApi('VN')),
('Yemen', 'YE', 'YEM', '+967', [dbo].FormatFlagApi('YE')),
('Zambia', 'ZM', 'ZMB', '+260', [dbo].FormatFlagApi('ZM')),
('Zimbabwe', 'ZW', 'ZWE', '+263', [dbo].FormatFlagApi('ZW'));
GO

DROP FUNCTION [dbo].FormatFlagApi;
GO