CREATE FUNCTION [dbo].FormatFlagApi (@inputString NVARCHAR(2))
RETURNS NVARCHAR(100)
AS
BEGIN
	RETURN N'https://flagsapi.com/' + @inputString + N'/flat/32.png';
END;
GO

INSERT INTO Country (Name, Iso2Code, Iso3Code, DialCode, FlagUrl) VALUES 
('Afghanistan', 'AF', 'AFG', '+93', [dbo].FormatFlagApi('AF')),
('Albania', 'AL', 'ALB', '+355', [dbo].FormatFlagApi('AL')),
('Algeria', 'DZ', 'DZA', '+213', [dbo].FormatFlagApi('DZ')),
('Andorra', 'AD', 'AND', '+376', [dbo].FormatFlagApi('AD')),
('Angola', 'AO', 'AGO', '+244', [dbo].FormatFlagApi('AO')),
('Antigua and Barbuda', 'AG', 'ATG', '+1-268', [dbo].FormatFlagApi('AG')),
('Argentina', 'AR', 'ARG', '+54', [dbo].FormatFlagApi('AR')),
('Armenia', 'AM', 'ARM', '+374', [dbo].FormatFlagApi('AM')),
('Australia', 'AU', 'AUS', '+61', [dbo].FormatFlagApi('AU')),
('Austria', 'AT', 'AUT', '+43', [dbo].FormatFlagApi('AT')),
('Azerbaijan', 'AZ', 'AZE', '+994', [dbo].FormatFlagApi('AZ')),
('Bahamas', 'BS', 'BHS', '+1-242', [dbo].FormatFlagApi('BS')),
('Bahrain', 'BH', 'BHR', '+973', [dbo].FormatFlagApi('BH')),
('Bangladesh', 'BD', 'BGD', '+880', [dbo].FormatFlagApi('BD')),
('Barbados', 'BB', 'BRB', '+1-246', [dbo].FormatFlagApi('BB')),
('Belarus', 'BY', 'BLR', '+375', [dbo].FormatFlagApi('BY')),
('Belgium', 'BE', 'BEL', '+32', [dbo].FormatFlagApi('BE')),
('Belize', 'BZ', 'BLZ', '+501', [dbo].FormatFlagApi('BZ')),
('Benin', 'BJ', 'BEN', '+229', [dbo].FormatFlagApi('BJ')),
('Bhutan', 'BT', 'BTN', '+975', [dbo].FormatFlagApi('BT')),
('Bolivia', 'BO', 'BOL', '+591', [dbo].FormatFlagApi('BO')),
('Bosnia and Herzegovina', 'BA', 'BIH', '+387', [dbo].FormatFlagApi('BA')),
('Botswana', 'BW', 'BWA', '+267', [dbo].FormatFlagApi('BW')),
('Brazil', 'BR', 'BRA', '+55', [dbo].FormatFlagApi('BR')),
('Brunei Darussalam', 'BN', 'BRN', '+673', [dbo].FormatFlagApi('BN')),
('Bulgaria', 'BG', 'BGR', '+359', [dbo].FormatFlagApi('BG')),
('Burkina Faso', 'BF', 'BFA', '+226', [dbo].FormatFlagApi('BF')),
('Burundi', 'BI', 'BDI', '+257', [dbo].FormatFlagApi('BI')),
('Cabo Verde', 'CV', 'CPV', '+238', [dbo].FormatFlagApi('CV')),
('Cambodia', 'KH', 'KHM', '+855', [dbo].FormatFlagApi('KH')),
('Cameroon', 'CM', 'CMR', '+237', [dbo].FormatFlagApi('CM')),
('Canada', 'CA', 'CAN', '+1', [dbo].FormatFlagApi('CA')),
('Central African Republic', 'CF', 'CAF', '+236', [dbo].FormatFlagApi('CF')),
('Chad', 'TD', 'TCD', '+235', [dbo].FormatFlagApi('TD')),
('Chile', 'CL', 'CHL', '+56', [dbo].FormatFlagApi('CL')),
('China', 'CN', 'CHN', '+86', [dbo].FormatFlagApi('CN')),
('Colombia', 'CO', 'COL', '+57', [dbo].FormatFlagApi('CO')),
('Comoros', 'KM', 'COM', '+269', [dbo].FormatFlagApi('KM')),
('Congo', 'CG', 'COG', '+242', [dbo].FormatFlagApi('CG')),
('Congo, Democratic Republic of the', 'CD', 'COD', '+243', [dbo].FormatFlagApi('CD')),
('Costa Rica', 'CR', 'CRI', '+506', [dbo].FormatFlagApi('CR')),
('Croatia', 'HR', 'HRV', '+385', [dbo].FormatFlagApi('HR')),
('Cuba', 'CU', 'CUB', '+53', [dbo].FormatFlagApi('CU')),
('Cyprus', 'CY', 'CYP', '+357', [dbo].FormatFlagApi('CY')),
('Czech Republic', 'CZ', 'CZE', '+420', [dbo].FormatFlagApi('CZ')),
('Denmark', 'DK', 'DNK', '+45', [dbo].FormatFlagApi('DK')),
('Djibouti', 'DJ', 'DJI', '+253', [dbo].FormatFlagApi('DJ')),
('Dominica', 'DM', 'DMA', '+1-767', [dbo].FormatFlagApi('DM')),
('Dominican Republic', 'DO', 'DOM', '+1-809', [dbo].FormatFlagApi('DO')),
('East Timor', 'TL', 'TLS', '+670', [dbo].FormatFlagApi('TL')),
('Ecuador', 'EC', 'ECU', '+593', [dbo].FormatFlagApi('EC')),
('Egypt', 'EG', 'EGY', '+20', [dbo].FormatFlagApi('EG')),
('El Salvador', 'SV', 'SLV', '+503', [dbo].FormatFlagApi('SV')),
('Equatorial Guinea', 'GQ', 'GNQ', '+240', [dbo].FormatFlagApi('GQ')),
('Eritrea', 'ER', 'ERI', '+291', [dbo].FormatFlagApi('ER')),
('Estonia', 'EE', 'EST', '+372', [dbo].FormatFlagApi('EE')),
('Eswatini', 'SZ', 'SWZ', '+268', [dbo].FormatFlagApi('SZ')),
('Ethiopia', 'ET', 'ETH', '+251', [dbo].FormatFlagApi('ET')),
('Fiji', 'FJ', 'FJI', '+679', [dbo].FormatFlagApi('FJ')),
('Finland', 'FI', 'FIN', '+358', [dbo].FormatFlagApi('FI')),
('France', 'FR', 'FRA', '+33', [dbo].FormatFlagApi('FR')),
('Gabon', 'GA', 'GAB', '+241', [dbo].FormatFlagApi('GA')),
('Gambia', 'GM', 'GMB', '+220', [dbo].FormatFlagApi('GM')),
('Georgia', 'GE', 'GEO', '+995', [dbo].FormatFlagApi('GE')),
('Germany', 'DE', 'DEU', '+49', [dbo].FormatFlagApi('DE')),
('Ghana', 'GH', 'GHA', '+233', [dbo].FormatFlagApi('GH')),
('Greece', 'GR', 'GRC', '+30', [dbo].FormatFlagApi('GR')),
('Grenada', 'GD', 'GRD', '+1-473', [dbo].FormatFlagApi('GD')),
('Guatemala', 'GT', 'GTM', '+502', [dbo].FormatFlagApi('GT')),
('Guinea', 'GN', 'GIN', '+224', [dbo].FormatFlagApi('GN')),
('Guinea-Bissau', 'GW', 'GNB', '+245', [dbo].FormatFlagApi('GW')),
('Guyana', 'GY', 'GUY', '+592', [dbo].FormatFlagApi('GY')),
('Haiti', 'HT', 'HTI', '+509', [dbo].FormatFlagApi('HT')),
('Honduras', 'HN', 'HND', '+504', [dbo].FormatFlagApi('HN')),
('Hungary', 'HU', 'HUN', '+36', [dbo].FormatFlagApi('HU')),
('Iceland', 'IS', 'ISL', '+354', [dbo].FormatFlagApi('IS')),
('India', 'IN', 'IND', '+91', [dbo].FormatFlagApi('IN')),
('Indonesia', 'ID', 'IDN', '+62', [dbo].FormatFlagApi('ID')),
('Iran', 'IR', 'IRN', '+98', [dbo].FormatFlagApi('IR')),
('Iraq', 'IQ', 'IRQ', '+964', [dbo].FormatFlagApi('IQ')),
('Ireland', 'IE', 'IRL', '+353', [dbo].FormatFlagApi('IE')),
('Israel', 'IL', 'ISR', '+972', [dbo].FormatFlagApi('IL')),
('Italy', 'IT', 'ITA', '+39', [dbo].FormatFlagApi('IT')),
('Jamaica', 'JM', 'JAM', '+1-876', [dbo].FormatFlagApi('JM')),
('Japan', 'JP', 'JPN', '+81', [dbo].FormatFlagApi('JP')),
('Jordan', 'JO', 'JOR', '+962', [dbo].FormatFlagApi('JO')),
('Kazakhstan', 'KZ', 'KAZ', '+7', [dbo].FormatFlagApi('KZ')),
('Kenya', 'KE', 'KEN', '+254', [dbo].FormatFlagApi('KE')),
('Kiribati', 'KI', 'KIR', '+686', [dbo].FormatFlagApi('KI')),
('Korea, North', 'KP', 'PRK', '+850', [dbo].FormatFlagApi('KP')),
('Korea, South', 'KR', 'KOR', '+82', [dbo].FormatFlagApi('KR')),
('Kosovo', 'XK', 'XKX', '+383', [dbo].FormatFlagApi('XK')),
('Kuwait', 'KW', 'KWT', '+965', [dbo].FormatFlagApi('KW')),
('Kyrgyzstan', 'KG', 'KGZ', '+996', [dbo].FormatFlagApi('KG')),
('Lao People''s Democratic Republic', 'LA', 'LAO', '+856', [dbo].FormatFlagApi('LA')),
('Latvia', 'LV', 'LVA', '+371', [dbo].FormatFlagApi('LV')),
('Lebanon', 'LB', 'LBN', '+961', [dbo].FormatFlagApi('LB')),
('Lesotho', 'LS', 'LSO', '+266', [dbo].FormatFlagApi('LS')),
('Liberia', 'LR', 'LBR', '+231', [dbo].FormatFlagApi('LR')),
('Libya', 'LY', 'LBY', '+218', [dbo].FormatFlagApi('LY')),
('Liechtenstein', 'LI', 'LIE', '+423', [dbo].FormatFlagApi('LI')),
('Lithuania', 'LT', 'LTU', '+370', [dbo].FormatFlagApi('LT')),
('Luxembourg', 'LU', 'LUX', '+352', [dbo].FormatFlagApi('LU')),
('Madagascar', 'MG', 'MDG', '+261', [dbo].FormatFlagApi('MG')),
('Malawi', 'MW', 'MWI', '+265', [dbo].FormatFlagApi('MW')),
('Malaysia', 'MY', 'MYS', '+60', [dbo].FormatFlagApi('MY')),
('Maldives', 'MV', 'MDV', '+960', [dbo].FormatFlagApi('MV')),
('Mali', 'ML', 'MLI', '+223', [dbo].FormatFlagApi('ML')),
('Malta', 'MT', 'MLT', '+356', [dbo].FormatFlagApi('MT')),
('Marshall Islands', 'MH', 'MHL', '+692', [dbo].FormatFlagApi('MH')),
('Mauritania', 'MR', 'MRT', '+222', [dbo].FormatFlagApi('MR')),
('Mauritius', 'MU', 'MUS', '+230', [dbo].FormatFlagApi('MU')),
('Mexico', 'MX', 'MEX', '+52', [dbo].FormatFlagApi('MX')),
('Micronesia', 'FM', 'FSM', '+691', [dbo].FormatFlagApi('FM')),
('Moldova', 'MD', 'MDA', '+373', [dbo].FormatFlagApi('MD')),
('Monaco', 'MC', 'MCO', '+377', [dbo].FormatFlagApi('MC')),
('Mongolia', 'MN', 'MNG', '+976', [dbo].FormatFlagApi('MN')),
('Montenegro', 'ME', 'MNE', '+382', [dbo].FormatFlagApi('ME')),
('Morocco', 'MA', 'MAR', '+212', [dbo].FormatFlagApi('MA')),
('Mozambique', 'MZ', 'MOZ', '+258', [dbo].FormatFlagApi('MZ')),
('Myanmar', 'MM', 'MMR', '+95', [dbo].FormatFlagApi('MM')),
('Namibia', 'NA', 'NAM', '+264', [dbo].FormatFlagApi('NA')),
('Nauru', 'NR', 'NRU', '+674', [dbo].FormatFlagApi('NR')),
('Nepal', 'NP', 'NPL', '+977', [dbo].FormatFlagApi('NP')),
('Netherlands', 'NL', 'NLD', '+31', [dbo].FormatFlagApi('NL')),
('New Zealand', 'NZ', 'NZL', '+64', [dbo].FormatFlagApi('NZ')),
('Nicaragua', 'NI', 'NIC', '+505', [dbo].FormatFlagApi('NI')),
('Niger', 'NE', 'NER', '+227', [dbo].FormatFlagApi('NE')),
('Nigeria', 'NG', 'NGA', '+234', [dbo].FormatFlagApi('NG')),
('North Macedonia', 'MK', 'MKD', '+389', [dbo].FormatFlagApi('MK')),
('Norway', 'NO', 'NOR', '+47', [dbo].FormatFlagApi('NO')),
('Oman', 'OM', 'OMN', '+968', [dbo].FormatFlagApi('OM')),
('Pakistan', 'PK', 'PAK', '+92', [dbo].FormatFlagApi('PK')),
('Palau', 'PW', 'PLW', '+680', [dbo].FormatFlagApi('PW')),
('Palestine', 'PS', 'PSE', '+970', [dbo].FormatFlagApi('PS')),
('Panama', 'PA', 'PAN', '+507', [dbo].FormatFlagApi('PA')),
('Papua New Guinea', 'PG', 'PNG', '+675', [dbo].FormatFlagApi('PG')),
('Paraguay', 'PY', 'PRY', '+595', [dbo].FormatFlagApi('PY')),
('Peru', 'PE', 'PER', '+51', [dbo].FormatFlagApi('PE')),
('Philippines', 'PH', 'PHL', '+63', [dbo].FormatFlagApi('PH')),
('Poland', 'PL', 'POL', '+48', [dbo].FormatFlagApi('PL')),
('Portugal', 'PT', 'PRT', '+351', [dbo].FormatFlagApi('PT')),
('Qatar', 'QA', 'QAT', '+974', [dbo].FormatFlagApi('QA')),
('Romania', 'RO', 'ROU', '+40', [dbo].FormatFlagApi('RO')),
('Russia', 'RU', 'RUS', '+7', [dbo].FormatFlagApi('RU')),
('Rwanda', 'RW', 'RWA', '+250', [dbo].FormatFlagApi('RW')),
('Saint Kitts and Nevis', 'KN', 'KNA', '+1-869', [dbo].FormatFlagApi('KN')),
('Saint Lucia', 'LC', 'LCA', '+1-758', [dbo].FormatFlagApi('LC')),
('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1-784', [dbo].FormatFlagApi('VC')),
('Samoa', 'WS', 'WSM', '+685', [dbo].FormatFlagApi('WS')),
('San Marino', 'SM', 'SMR', '+378', [dbo].FormatFlagApi('SM')),
('Sao Tome and Principe', 'ST', 'STP', '+239', [dbo].FormatFlagApi('ST')),
('Saudi Arabia', 'SA', 'SAU', '+966', [dbo].FormatFlagApi('SA')),
('Senegal', 'SN', 'SEN', '+221', [dbo].FormatFlagApi('SN')),
('Serbia', 'RS', 'SRB', '+381', [dbo].FormatFlagApi('RS')),
('Seychelles', 'SC', 'SYC', '+248', [dbo].FormatFlagApi('SC')),
('Sierra Leone', 'SL', 'SLE', '+232', [dbo].FormatFlagApi('SL')),
('Singapore', 'SG', 'SGP', '+65', [dbo].FormatFlagApi('SG')),
('Slovakia', 'SK', 'SVK', '+421', [dbo].FormatFlagApi('SK')),
('Slovenia', 'SI', 'SVN', '+386', [dbo].FormatFlagApi('SI')),
('Solomon Islands', 'SB', 'SLB', '+677', [dbo].FormatFlagApi('SB')),
('Somalia', 'SO', 'SOM', '+252', [dbo].FormatFlagApi('SO')),
('South Africa', 'ZA', 'ZAF', '+27', [dbo].FormatFlagApi('ZA')),
('South Sudan', 'SS', 'SSD', '+211', [dbo].FormatFlagApi('SS')),
('Spain', 'ES', 'ESP', '+34', [dbo].FormatFlagApi('ES')),
('Sri Lanka', 'LK', 'LKA', '+94', [dbo].FormatFlagApi('LK')),
('Sudan', 'SD', 'SDN', '+249', [dbo].FormatFlagApi('SD')),
('Suriname', 'SR', 'SUR', '+597', [dbo].FormatFlagApi('SR')),
('Sweden', 'SE', 'SWE', '+46', [dbo].FormatFlagApi('SE')),
('Switzerland', 'CH', 'CHE', '+41', [dbo].FormatFlagApi('CH')),
('Syria', 'SY', 'SYR', '+963', [dbo].FormatFlagApi('SY')),
('Taiwan', 'TW', 'TWN', '+886', [dbo].FormatFlagApi('TW')),
('Tajikistan', 'TJ', 'TJK', '+992', [dbo].FormatFlagApi('TJ')),
('Tanzania', 'TZ', 'TZA', '+255', [dbo].FormatFlagApi('TZ')),
('Thailand', 'TH', 'THA', '+66', [dbo].FormatFlagApi('TH')),
('Togo', 'TG', 'TGO', '+228', [dbo].FormatFlagApi('TG')),
('Tonga', 'TO', 'TON', '+676', [dbo].FormatFlagApi('TO')),
('Trinidad and Tobago', 'TT', 'TTO', '+1-868', [dbo].FormatFlagApi('TT')),
('Tunisia', 'TN', 'TUN', '+216', [dbo].FormatFlagApi('TN')),
('Turkey', 'TR', 'TUR', '+90', [dbo].FormatFlagApi('TR')),
('Turkmenistan', 'TM', 'TKM', '+993', [dbo].FormatFlagApi('TM')),
('Tuvalu', 'TV', 'TUV', '+688', [dbo].FormatFlagApi('TV')),
('Uganda', 'UG', 'UGA', '+256', [dbo].FormatFlagApi('UG')),
('Ukraine', 'UA', 'UKR', '+380', [dbo].FormatFlagApi('UA')),
('United Arab Emirates', 'AE', 'ARE', '+971', [dbo].FormatFlagApi('AE')),
('United Kingdom', 'GB', 'GBR', '+44', [dbo].FormatFlagApi('GB')),
('United States of America', 'US', 'USA', '+1', [dbo].FormatFlagApi('US')),
('Uruguay', 'UY', 'URY', '+598', [dbo].FormatFlagApi('UY')),
('Uzbekistan', 'UZ', 'UZB', '+998', [dbo].FormatFlagApi('UZ')),
('Vanuatu', 'VU', 'VUT', '+678', [dbo].FormatFlagApi('VU')),
('Vatican City', 'VA', 'VAT', '+379', [dbo].FormatFlagApi('VA')),
('Venezuela', 'VE', 'VEN', '+58', [dbo].FormatFlagApi('VE')),
('Vietnam', 'VN', 'VNM', '+84', [dbo].FormatFlagApi('VN')),
('Yemen', 'YE', 'YEM', '+967', [dbo].FormatFlagApi('YE')),
('Zambia', 'ZM', 'ZMB', '+260', [dbo].FormatFlagApi('ZM')),
('Zimbabwe', 'ZW', 'ZWE', '+263', [dbo].FormatFlagApi('ZW'));
GO

DROP FUNCTION [dbo].FormatFlagApi;
GO